In [20]:
##########################################################################

#Title: Beginner's approach to Cleaning Text & Assessing Sentiment 
#By: b.hogan@snhu.edu
#Purpose:    For training purposes: basic tweet cleaning, labeling, sentiment
#            score w vadar, Turker Sentiment, Worker Kappa Agreement using
#            either Cohen or Krippendorf
"""
NLTK Vadar: http://www.nltk.org/_modules/nltk/sentiment/vader.html
#scores text positive, negative, and neutral. It also gives a cmpd
#score, which should be overall sentiment, ranging from -1 (neg) to +1 (pos).

Cohen’s kappa: a statistic that measures inter-annotator agreement.
https://scikit-learn.org/stable/modules/generated/sklearn.metrics.cohen_kappa_score.html
    y1array, shape = [n_samples]
    Labels assigned by the first annotator.
    y2array, shape = [n_samples]
    Labels assigned by the second annotator

Krippendorff:For inter-rater agreements for experimental data with missing 
      values, Krippendorff's alpha coef. established as a standard measure.
      https://github.com/grrrr/krippendorff-alpha
      
      #Text  ...        Label creation time
# 0  NIck's Pizza Port. Had heard about this ...  ...  May 23, 2020, 7:31 AM UTC
# 1  Tokyo Star Sushi. I really like this buf...  ...  May 23, 2020, 7:29 AM UTC

#Choice a: Clearn in Excel
#Choice B: Clean in Python ==> simply depends if need engineering in future

##########################################################################"""

"\nNLTK Vadar: http://www.nltk.org/_modules/nltk/sentiment/vader.html\n#scores text positive, negative, and neutral. It also gives a cmpd\n#score, which should be overall sentiment, ranging from -1 (neg) to +1 (pos).\n\nCohen’s kappa: a statistic that measures inter-annotator agreement.\nhttps://scikit-learn.org/stable/modules/generated/sklearn.metrics.cohen_kappa_score.html\n    y1array, shape = [n_samples]\n    Labels assigned by the first annotator.\n    y2array, shape = [n_samples]\n    Labels assigned by the second annotator\n\nKrippendorff:For inter-rater agreements for experimental data with missing \n      values, Krippendorff's alpha coef. established as a standard measure.\n      https://github.com/grrrr/krippendorff-alpha\n      \n      #Text  ...        Label creation time\n# 0  NIck's Pizza Port. Had heard about this ...  ...  May 23, 2020, 7:31 AM UTC\n# 1  Tokyo Star Sushi. I really like this buf...  ...  May 23, 2020, 7:29 AM UTC\n\n#Choice a: Clearn in Excel\n#Choice B

In [17]:
import os
import numpy as np
import pandas as pd
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import re
print("done")

done


In [21]:
#####################################################turk###############
#===> Step 1: Preprocessing & Data Inspection
####################################################################"""
os.getcwd()
os.chdir("C:\\Users\\17574\\Desktop\\Dave_Tutoriong")

#Quickly view data 
#df = pd.read_csv("C:\\Users\\17574\\Desktop\\Dave_Tutoriong\\rawdata.csv")
#df.columns #Index(['Text', 'Label', 'Source', 'Confidence', 'Label creation time'], dtype='object')
#df[['Text','Label']]   #panda dataframe subtyping approach
#df
""" ####################################################################
===> Step 2: Text Cleaning & Addressing Feature Removal such as stopwords
    ####################################################################"""
rawfilename = "rawdata.csv"
FILE = open(rawfilename, "r")  #encoding = "ISO-8859-1") 
filename = "a_mycleandata.csv" #clean then write it back to csv!need empty csv file
NEWFILE = open(filename, "w") ##in 1st row create lable & text columns
towrite = "Label, Text\n"      ##"""write this to new empty csv file"""
NEWFILE.write(towrite)
NEWFILE.close()
NEWFILE = open(filename, "a") 
myfinaldf = pd.DataFrame()
outputfile = "a_details_mycleandata.txt"
OUTFILE = open(outputfile, "w") 
OUTFILE.close()
OUTFILE = open(outputfile,"a")

remove_stopwords=0  #set to 1 for using nltk for english stopwords
sentences=[]
mylabel=[]
for row in FILE:   ##going line by line
    rawrow="\n\nThe row is: " + row + "\n"
    OUTFILE.write(rawrow) ##i am going to write this again later for comp
    row = row.lstrip()  #strip all space from the left
    row = row.rstrip()  ##strip all the space fro the right
    row = row.strip() #strip all extra spaces in general
    mylist = row.split(" ")
    #print(mylist)
    #clean and put results in new list
    newlist = []
    for word in mylist:
        #print("the new word is: ",word)
        placeinoutputfile = "The next word before is: " + word + "\n"
        OUTFILE.write(placeinoutputfile)
        word = word.lower()
        word = word.lstrip()
        word = word.strip("\n")
        word = word.strip("\\n")
        word = word.replace(",","")
        word = word.replace(" ","")
        word = word.replace("_","")
        word = re.sub('\+', '',word)
        word = re.sub('.*\+\n','',word)   ##LOOKS FUNNY! single quotes!
        word = re.sub('zz+','',word)
        word = word.replace("\t","")
        word = word.replace(".","")
        word = word.replace("\'s","")  #was comment3d out
        word = word.strip()
        
        newlist.append(word)
        #word.replace("\","")  #was commented out
        if remove_stopwords == 1: 
            if word not in["","\\","'","*",":",";"]:
                if len(word) <1:
                    if not re.search(r'\d',word): ##remove the digits
                        # HW2 ===non english words
                        if remove_stopwords==1:  #code to remove nonenglish words
                            if word in nltk_words.words():
                                word= word
                            else:
                                word = ""
                        if remove_stopwords==1:
                            stop_words=set(stopwords.words("english"))
                            if word not in stop_words:
                                word = word
                        newlist.append(word)
                        placeinoutputfil = "The next word AFTER is: " + word + "\n"
                        OUTFILE.write(placeinoutputfile)
                        #NOW WE HAVE ALL THE WORDS   
            ###if super stuck the following will delete the entire line and move forward
            #if word not in["","\\","'","*",":",";"]:
            #    word =""
    #print(newlist)
    #print(newlist[-1])  #the last element = the label
    label = newlist[-1]
    if "positive" in label:   # change to "pos"   or "neg" depend on file
        label = "1"
    if "negative" in label:   # change to "pos"   or "neg" depend on file
        label = "0"
    mylabel.append(label)
#    placeinoutputfile = "\n The label is: " + label + "\n"
#    OUTFILE.write(placeinoutputfile)
    """remove the last item which is the label with pop command"""
    newlist.pop()  
    text = " ".join(newlist)
    #placeinoutputfile = "\n The Text is: " + Text + "\n"
    #OUTFILE.write(placeinoutputfile)
    #print(text)
    #print("LABEL\n"
    #print(label)
    ## MORE CLEANING
#    text = text.replace("\\n","")
#    text = text.strip("\\n")
#    text = text.replace("\\'","")
#    text = text.replace("\\","")
#    text = text.replace("''","")
#    text = text.replace("'","")
#    text = text.replace("s'","")
#    text = text.lstrip()
    
    originalrow = "ORIGINAL" + rawrow
    OUTFILE.write(originalrow)
    towrite = label+","+text+"\n"
    NEWFILE.write(towrite)
    OUTFILE.write(towrite)
    sentences.append(text)
    
FILE.close()       ##alwasy  the files!
NEWFILE.close()
OUTFILE.close()
print(mylabel)
print(sentences)
len(sentences)
len(mylabel)

['0', '1', '0', '0', '0', '1', '1', '0', '1']
['ick pia port had heard about this ', 'tokyo star sushi i really like this buf', 'after i went shopping with some of my fr', '"wow olive oil garde was very disappoi', 'seventh heave restaurant was ever know', 'i went to dave restaurant and loved it', 'i went to tommy burger and pasta restaur', 'i went to the chilis o alto blvd and h', 'omg this restaurant the receptionist g']


9

In [22]:
""" ####################################################################
===> Step 3: Get Vadar scores to compare against Turkers, aka ground truth
    ####################################################################"""
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer
#from vader_lexicon import SentimentIntensityAnalyzer
sid=SentimentIntensityAnalyzer()
score = []
for sentence in sentences:
    #print(sentence)
    ss=sid.polarity_scores(sentence)
    score.append(ss)
#    for k in sorted(ss):
#        #print('{0}:{1},'.format(k,ss[k]),end=' ') #single quote not a double
#        score.append(ss)
len(score)        
vadar_score_df = pd.DataFrame(score) #use DF to aggregate
print(vadar_score_df)
#score_result.shape
#df_output = pd.DataFrame(score_result)
#df_output.to_csv("a_vadar_ground_truth.csv", index=True)


   neg    neu    pos  compound
0  0.0  1.000  0.000    0.0000
1  0.0  0.682  0.318    0.4201
2  0.0  1.000  0.000    0.0000
3  0.0  0.612  0.388    0.5859
4  0.0  1.000  0.000    0.0000
5  0.0  0.606  0.394    0.5994
6  0.0  1.000  0.000    0.0000
7  0.0  1.000  0.000    0.0000
8  0.0  1.000  0.000    0.0000


[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\17574\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


In [26]:
""" ######################################################################
===> Step 4: Get Turker Kappa for agreement amongst workers
    ######################################################################"""
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import confusion_matrix

df = pd.read_csv("C:\\Users\\17574\\Desktop\\Dave_Tutoriong\\turker_author_labels.csv")
df.columns
df


""" y stands for vector, ie a worker or author's label """
y1=[]; y2=[]; y3=[]; y4=[]   #vector variable
y1 = df['turker_1'].tolist()
y2 = df['turker_2'].tolist() #fill w data
y3 = df['turker_3'].tolist()
y4 = df['author'].tolist()
y5 = abs(round(vadar_score_df['compound'],0)).tolist()  #vadar
"""calculated the stats between pairs"""
y1z1=round(cohen_kappa_score(y1,y2),2) #calc stats
y1z2=round(cohen_kappa_score(y1,y3),2)
y1z3=round(cohen_kappa_score(y1,y4),2)
y1z4=round(cohen_kappa_score(y1,y5),2)
y2z1=round(cohen_kappa_score(y2,y1),2) 
y2z2=round(cohen_kappa_score(y2,y3),2)
y2z3=round(cohen_kappa_score(y2,y4),2)
y2z4=round(cohen_kappa_score(y2,y4),2)
y3z1=round(cohen_kappa_score(y3,y2),2) 
y3z2=round(cohen_kappa_score(y3,y1),2)
y3z3=round(cohen_kappa_score(y3,y4),2)
y3z4=round(cohen_kappa_score(y3,y5),2)
print("Manual Kappa Turkers and Author:")
print(y1z1, y1z2, y1z3, y1z4,y2z1, y2z2, y2z3, y2z4,y3z1, y3z2, y3z3, y3z4) #inspect

# ==> github help https://github.com/grrrr/krippendorff-alpha
import krippendorff  #pip install krippendorff
import numpy as np
value_counts = np.array(df) #use a numpy array with the output for calc
value_counts
print("Krippendorff's alpha: 1=perfect, 0=no reliability, <0 systematic disagreement",krippendorff.alpha(value_counts=value_counts, level_of_measurement='nominal'))


Manual Kappa Turkers and Author:
0.28 -0.11 -0.29 0.36 0.28 -0.12 -0.29 -0.29 -0.12 -0.11 -0.26 -0.26
Krippendorff's alpha: 1=perfect, 0=no reliability, <0 systematic disagreement -0.08455284552845543


In [27]:
""" ########################################################### #########
===> Ground Truth to Vadar to Turkers
    ####################################################################"""
y6=round(((df['turker_1']+df['turker_2']+df['turker_3'])/3),0).tolist()
#y4=author
#y5=vadar
mykappa_author_vs_turkers=cohen_kappa_score(y4,y6) #author vs turkers
mykappa_turkers_vs_vadar = cohen_kappa_score(y6,y5)
print("author vs turkers kappa",round(mykappa_author_vs_turkers,2))
print("author vs turkers confusionmatrix: \n",confusion_matrix(y1, y2))
print("turkers vs vadar kappa: ", round(mykappa_turkers_vs_vadar,2))
print("turkers vs vadar confusionmatrix: \n",confusion_matrix(y2, y3))
print("Krippendorff's alpha GroundTruth: ", krippendorff.alpha(value_counts=value_counts))


author vs turkers kappa -0.15
author vs turkers confusionmatrix: 
 [[3 3 1]
 [0 2 0]
 [0 0 0]]
turkers vs vadar kappa:  -0.05
turkers vs vadar confusionmatrix: 
 [[1 2 0]
 [1 2 2]
 [0 1 0]]
Krippendorff's alpha GroundTruth:  0.07161458333333337
